# Display a sponsor button on the repo when GitHub Sponsors is enabled.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [foisalislambd]
