package catalog

// Providers from https://github.com/zebbern/no-cost-ai that were not already
// in the generated catalog. Chat sites and media studios without an
// OpenAI-compatible API stay unsupported: the panel can list them, and a
// chat call explains that this router cannot complete it.

func nocostProviders() []Provider {
	return []Provider{
		{
			Slug:           "eqing",
			DisplayName:    "Eqing",
			Protocol:       ProtocolOpenAIChat,
			DefaultBaseURL: "https://origin.eqing.tech/v1",
			DocsURL:        "https://origin.eqing.tech",
			Summary:        "Signup chat site with an OpenAI-compatible API. Save the account key, then call https://origin.eqing.tech/v1. Backup host is https://site.eqing.tech/v1. Listing models does not grant chat access. Use Load models after the key is saved.",
			Category:       "Gateway",
			Free:           true,
			Models: namedModels("Eqing", KindChat,
				"grok-4.1-fast-free",
				"z-free",
				"gemini-3-flash",
				"gpt-5-6-all",
				"gpt-6-luna-wm-max",
				"claude-sonnet-5",
				"claude-opus-5",
				"gemini-3.1-pro",
				"grok-4.5",
				"gpt-5-5-thinking-extended",
				"gpt-5-5-thinking-max",
				"gpt-5-6-thinking-extended",
				"gpt-5-6-thinking-max",
				"gpt-6-sol-wm-extended",
				"gpt-5.5(xhigh)",
				"gpt-5.6-sol(xhigh)",
			),
		},
		{
			Slug:           "g4f",
			DisplayName:    "g4f.space",
			Protocol:       ProtocolOpenAIChat,
			DefaultBaseURL: "https://g4f.space/v1",
			DocsURL:        "https://g4f.dev/docs/ready_to_use.html",
			Summary:        "Hosted g4f gateway. Create a member key at https://g4f.dev/api_key.html. Model ids change often; use Load models to refresh the list.",
			Category:       "Gateway",
			Free:           true,
			Models: namedModels("g4f.space", KindChat,
				"auto",
				"openai/gpt-oss-120b",
				"gpt-oss:20b-cloud",
				"gemini-3-flash",
				"gemini-3.1-pro-high",
				"gemini-3.8-flash",
				"kimi-k3",
				"moonshotai/Kimi-K3",
				"claude-sonnet-5.5",
				"codestral-2508",
			),
		},
		{
			Slug:           "g4f-grok",
			DisplayName:    "g4f.space Grok",
			Protocol:       ProtocolOpenAIChat,
			DefaultBaseURL: "https://g4f.space/api/grok/v1",
			DocsURL:        "https://g4f.dev/docs/ready_to_use.html",
			Summary:        "g4f.space proxy for Grok. Anonymous access may need cake credits from g4f.dev/chat, or a g4f.dev member key.",
			Category:       "Gateway",
			Free:           true,
			Models:         namedModels("g4f.space Grok", KindChat, "fast", "auto", "heavy", "expert"),
		},
		{
			Slug:           "ollamafreeapi",
			DisplayName:    "OllamaFreeAPI",
			Protocol:       ProtocolOpenAIChat,
			DefaultBaseURL: "http://127.0.0.1:8000/v1",
			DocsURL:        "https://github.com/mfoud444/ollamafreeapi",
			Summary:        "Local OpenAI proxy. Run that project's server.py, then keep this base URL on http://127.0.0.1:8000/v1. No key. The model list is whatever the proxy can reach.",
			Category:       "Local",
			Free:           true,
			KeyOptional:    true,
			Models: namedModels("OllamaFreeAPI", KindChat,
				"llama3.2:3b",
				"deepseek-r1:latest",
				"gpt-oss:20b",
				"mistral:latest",
				"mistral-nemo:custom",
				"bakllava:latest",
				"smollm2:135m",
			),
		},
		site("sharedchat", "SharedChat", "https://sharedchat.cn",
			"Shared web chat for gpt-4o, o3, o3-pro, o4-mini, and o4-mini-high. No public API, so this router cannot call it.",
			namedModels("SharedChat", KindChat, "gpt-4o", "o3", "o3-pro", "o4-mini", "o4-mini-high")),
		site("flowgpt", "FlowGPT", "https://flowgpt.com",
			"Community GPT website. No public API, so this router cannot call it.",
			nil),
		site("wsupai", "WsupAI", "https://wsupai.app",
			"No-signup character chat. No public API, so this router cannot call it.",
			nil),
		site("heck", "Heck.ai", "https://heck.ai",
			"No-signup chat site. About 50 queries a day and 5 search queries a day. Its web chat is not an OpenAI-compatible API, so this router cannot call it.",
			namedModels("Heck.ai", KindChat,
				"deepseek-v3",
				"deepseek-r1-pro",
				"gemini-2.5-flash",
				"chatgpt-4o-mini",
				"chatgpt-4.1-mini",
				"grok-3-mini",
				"llama-4-scout",
			)),
		site("free2gpt-gemini", "Free2GPT Gemini", "https://chat2.free2gpt.com",
			"No-signup Gemini chat page. No public API, so this router cannot call it.",
			namedModels("Free2GPT Gemini", KindChat, "gemini")),
		site("free2gpt", "Free2GPT", "https://chat4.free2gpt.com",
			"No-signup chat page. No public API, so this router cannot call it.",
			namedModels("Free2GPT", KindChat,
				"gpt-4o-mini",
				"wbot-t1-mini",
				"wbot-4-347b",
				"deepseek-chat",
				"deepseek-coder",
				"ds-r1-distill-70b",
				"wbot-2",
				"wbot-2-friend",
			)),
		site("netfly", "Netfly", "https://free.netfly.top",
			"No-signup GPT-4o mini chat page. No public API, so this router cannot call it.",
			namedModels("Netfly", KindChat, "gpt-4o-mini")),
		site("ai365vip", "AI365", "https://chat.ai365vip.com",
			"No-signup GPT-4o chat page. No public API, so this router cannot call it.",
			namedModels("AI365", KindChat, "gpt-4o")),
		site("theoldllm", "The Old LLM", "https://theoldllm.vercel.app",
			"No-signup chat page. Models and limits are unpublished, and there is no API this router can call.",
			nil),
		site("vheer", "Vheer", "https://vheer.com",
			"No-signup image site. No public API, so this router cannot call it.",
			namedModels("Vheer", KindImage, "image")),
		site("perchance", "Perchance", "https://perchance.org/wtr90dexsn",
			"No-signup image page that uses Pollinations. For an API, use the Pollinations provider. This page itself is not callable.",
			namedModels("Perchance", KindImage, "image")),
		site("fotor", "Fotor", "https://www.fotor.com",
			"Image editor with an AI option. No chat or generation API this router can call.",
			namedModels("Fotor", KindImage, "image")),
		site("ttsmp3", "TTSMP3", "https://ttsmp3.com",
			"Browser text-to-speech for short Google and Microsoft voices. No API this router can call.",
			namedModels("TTSMP3", KindAudio, "speech")),
		site("voicegenerator", "VoiceGenerator", "https://voicegenerator.io",
			"Browser text-to-speech with a length cap. No API this router can call.",
			namedModels("VoiceGenerator", KindAudio, "speech")),
		site("fakeyou", "FakeYou", "https://fakeyou.com",
			"Community voice site. Jobs are queued and rate limited. Its API is not the OpenAI speech route this router speaks.",
			namedModels("FakeYou", KindAudio, "speech")),
		site("yupp", "Yupp", "https://yupp.ai",
			"Signup chat site. Use continues while feedback credits last. No OpenAI-compatible API this router can call.",
			nil),
		site("lobechat", "LobeChat", "https://lobechat.com",
			"Chat app. It does not host these models; you connect your own provider keys inside LobeChat.",
			namedModels("LobeChat", KindChat,
				"gemini-2.5-pro",
				"gemini-2.5-flash",
				"gemini-2.0-flash-exp-image-generation",
				"deepseek-chat",
				"deepseek-reasoner",
				"kimi-k2-0711-preview",
			)),
		site("writesonic", "Writesonic", "https://writesonic.com/chat",
			"Signup chat with a monthly credit allowance. No OpenAI-compatible API on this chat page.",
			namedModels("Writesonic", KindChat, "claude-sonnet-3.5", "gpt-4o", "claude-opus", "claude-3-haiku", "gpt-4o-mini")),
		site("character-ai", "Character.AI", "https://character.ai",
			"Signup character chat. Replies can be slow and ads may appear. No API this router can call.",
			namedModels("Character.AI", KindChat, "character")),
		site("bing-create", "Bing Image Creator", "https://www.bing.com/images/create",
			"Microsoft image site for DALL-E 3 and related models. No API this router can call. Designer credits are separate.",
			namedModels("Bing Image Creator", KindImage, "dall-e-3", "mai-image-1", "gpt-4o")),
		site("microsoft-designer", "Microsoft Designer", "https://designer.microsoft.com",
			"Image site with a small monthly credit grant for personal use. No API this router can call.",
			namedModels("Microsoft Designer", KindImage, "dall-e-3")),
		site("pika", "Pika", "https://pika.art",
			"Signup video site. About 80 credits a month, with a watermark. No API this router can call.",
			namedModels("Pika", KindVideo, "pika-1.5", "pika-2.5")),
		site("krea", "Krea", "https://www.krea.ai",
			"Signup image site. About 50 generations a day, with a watermark. No API this router can call.",
			namedModels("Krea", KindImage, "krea-1", "flux.1-krea")),
		site("pixverse", "PixVerse", "https://app.pixverse.ai",
			"Signup video site. About 50 to 60 clips a day, with a watermark. No API this router can call.",
			namedModels("PixVerse", KindVideo, "video")),
		site("genmo", "Genmo", "https://www.genmo.ai",
			"Signup video site for Mochi. About 50 credits a month, with a watermark. No API this router can call.",
			namedModels("Genmo", KindVideo, "mochi-1")),
		site("stable-audio", "Stable Audio", "https://stableaudio.com",
			"Signup music site. Clips are short and monthly use is capped. No API this router can call.",
			namedModels("Stable Audio", KindAudio, "stable-audio-open")),
		site("riffusion", "Riffusion", "https://www.riffusion.com",
			"Signup music site with limited generations. No API this router can call.",
			namedModels("Riffusion", KindAudio, "riffusion")),
		site("uberduck", "Uberduck", "https://www.uberduck.ai",
			"Signup voice site billed in credits. No OpenAI speech API this router can call.",
			namedModels("Uberduck", KindAudio, "speech")),
		site("rovo", "Rovo Dev", "https://www.atlassian.com/software/rovo-dev",
			"Atlassian IDE agents. The free beta is a product login, not an API this router can call.",
			namedModels("Rovo Dev", KindChat, "claude-sonnet-4", "claude-opus-4")),
	}
}

func site(slug, name, docs, summary string, models []Model) Provider {
	return Provider{
		Slug:        slug,
		DisplayName: name,
		Protocol:    ProtocolUnsupported,
		DocsURL:     docs,
		Summary:     summary,
		Category:    "Website",
		Free:        true,
		KeyOptional: true,
		Models:      models,
	}
}

func namedModels(owner, kind string, ids ...string) []Model {
	label := owner + " model"
	switch kind {
	case KindImage:
		label = "Image model"
	case KindVideo:
		label = "Video model"
	case KindAudio:
		label = "Audio model"
	}
	models := make([]Model, 0, len(ids))
	for _, id := range ids {
		models = append(models, Model{
			UpstreamID:  id,
			DisplayName: id,
			Description: label,
			Kind:        kind,
		})
	}
	return models
}
