export type ProviderIcon = { file: string; white: boolean }

const icons: Record<string, ProviderIcon> = {
  "302-ai": { file: "302-ai", white: false },
  "360ai": { file: "360ai", white: false },
  "9router": { file: "9router", white: false },
  abacus: { file: "abacus", white: false },
  "adapta-web": { file: "adapta-web", white: false },
  "adobe-firefly": { file: "adobe-firefly", white: false },
  agentrouter: { file: "agentrouter", white: false },
  agnes: { file: "agnes", white: false },
  agy: { file: "agy", white: false },
  ai21: { file: "ai21", white: false },
  aiand: { file: "aiand", white: false },
  aihorde: { file: "aihorde", white: false },
  aihubmix: { file: "aihubmix", white: false },
  aimlapi: { file: "aimlapi", white: false },
  ainative: { file: "ainative", white: false },
  aionlabs: { file: "aionlabs", white: false },
  aiwave: { file: "aiwave", white: false },
  akashml: { file: "akashml", white: false },
  aki: { file: "aki", white: false },
  "aleph-alpha": { file: "aleph-alpha", white: false },
  alibaba: { file: "alibaba", white: false },
  "amazon-nova": { file: "amazon-nova", white: false },
  "amazon-q": { file: "amazon-q", white: false },
  ambient: { file: "ambient", white: false },
  "amd-token-factory": { file: "amd-token-factory", white: false },
  "ant-ling": { file: "ant-ling", white: false },
  anthropic: { file: "anthropic", white: false },
  antigravity: { file: "antigravity", white: false },
  anyapi: { file: "anyapi", white: false },
  anyscale: { file: "anyscale", white: false },
  "anysearch-search": { file: "anysearch-search", white: false },
  "api-airforce": { file: "api-airforce", white: false },
  apisix: { file: "apisix", white: false },
  "arcee-ai": { file: "arcee-ai", white: false },
  arcee: { file: "arcee", white: false },
  assemblyai: { file: "assemblyai", white: false },
  atlascloud: { file: "atlascloud", white: false },
  "atomic-chat": { file: "atomic-chat", white: false },
  auggie: { file: "auggie", white: false },
  auriko: { file: "auriko", white: false },
  aws: { file: "aws", white: false },
  axiom: { file: "axiom", white: false },
  azure: { file: "azure", white: false },
  azureai: { file: "azureai", white: false },
  bai: { file: "bai", white: false },
  baichuan: { file: "baichuan", white: false },
  baidu: { file: "baidu", white: false },
  bailian: { file: "bailian", white: false },
  baseten: { file: "baseten", white: false },
  bazaarlink: { file: "bazaarlink", white: false },
  bedrock: { file: "bedrock", white: false },
  berget: { file: "berget", white: false },
  bifrost: { file: "bifrost", white: false },
  "black-forest-labs": { file: "black-forest-labs", white: false },
  "blackbox-web": { file: "blackbox-web", white: false },
  blackbox: { file: "blackbox", white: false },
  bluesminds: { file: "bluesminds", white: false },
  braintrust: { file: "braintrust", white: false },
  "brave-search": { file: "brave-search", white: false },
  bria: { file: "bria", white: false },
  byteplus: { file: "byteplus", white: false },
  bytez: { file: "bytez", white: false },
  cartesia: { file: "cartesia", white: false },
  cerebras: { file: "cerebras", white: false },
  "charm-hyper": { file: "charm-hyper", white: false },
  "chat-oripe": { file: "chat-oripe", white: false },
  chatanywhere: { file: "chatanywhere", white: false },
  cheaperinference: { file: "cheaperinference", white: false },
  chenzk: { file: "chenzk", white: false },
  chipotle: { file: "chipotle", white: false },
  chutes: { file: "chutes", white: false },
  clarifai: { file: "clarifai", white: false },
  "claude-web": { file: "claude-web", white: false },
  claude: { file: "claude", white: false },
  "cli-generic": { file: "cli-generic", white: false },
  cline: { file: "cline", white: false },
  clinepass: { file: "clinepass", white: false },
  cliproxyapi: { file: "cliproxyapi", white: false },
  "cloudcode-one": { file: "cloudcode-one", white: false },
  cloudferro: { file: "cloudferro", white: false },
  cloudflare: { file: "cloudflare", white: false },
  cloudrift: { file: "cloudrift", white: false },
  "clova-studio": { file: "clova-studio", white: false },
  "codebuddy-cn": { file: "codebuddy-cn", white: false },
  codestral: { file: "codestral", white: false },
  codex: { file: "codex", white: false },
  cohere: { file: "cohere", white: false },
  cometapi: { file: "cometapi", white: false },
  comfyui: { file: "comfyui", white: false },
  "command-code": { file: "command-code", white: false },
  "conol-web": { file: "conol-web", white: false },
  context7: { file: "context7", white: false },
  continue: { file: "continue", white: false },
  copilot: { file: "copilot", white: false },
  coralbricks: { file: "coralbricks", white: false },
  cortecs: { file: "cortecs", white: false },
  coze: { file: "coze", white: false },
  crof: { file: "crof", white: false },
  crossmodel: { file: "crossmodel", white: false },
  crusoe: { file: "crusoe", white: false },
  cursor: { file: "cursor", white: false },
  dahl: { file: "dahl", white: false },
  "dasha-compute": { file: "dasha-compute", white: false },
  databricks: { file: "databricks", white: false },
  datarobot: { file: "datarobot", white: false },
  deepai: { file: "deepai", white: false },
  deepgram: { file: "deepgram", white: false },
  deepinfra: { file: "deepinfra", white: false },
  deepseek: { file: "deepseek", white: false },
  "devin-cli-agentic": { file: "devin-cli-agentic", white: false },
  "devin-cli": { file: "devin-cli", white: false },
  "devin-desktop": { file: "devin-desktop", white: false },
  devin: { file: "devin", white: false },
  dgrid: { file: "dgrid", white: false },
  dify: { file: "dify", white: false },
  digitalocean: { file: "digitalocean", white: false },
  dinference: { file: "dinference", white: false },
  discountedtokens: { file: "discountedtokens", white: false },
  dit: { file: "dit", white: false },
  "docker-model-runner": { file: "docker-model-runner", white: false },
  doubao: { file: "doubao", white: false },
  drun: { file: "drun", white: false },
  "duckduckgo-web": { file: "duckduckgo-web", white: false },
  dxnt: { file: "dxnt", white: false },
  ebcloud: { file: "ebcloud", white: false },
  "eden-ai": { file: "eden-ai", white: false },
  electronhub: { file: "electronhub", white: false },
  elevenlabs: { file: "elevenlabs", white: false },
  empiriolabs: { file: "empiriolabs", white: false },
  empower: { file: "empower", white: false },
  "envoy-agent-router": { file: "envoy-agent-router", white: false },
  eurouter: { file: "eurouter", white: false },
  evroc: { file: "evroc", white: false },
  exa: { file: "exa", white: false },
  factory: { file: "factory", white: false },
  fal: { file: "fal", white: false },
  fastrouter: { file: "fastrouter", white: false },
  "featherless-ai": { file: "featherless-ai", white: false },
  fenayai: { file: "fenayai", white: false },
  firecrawl: { file: "firecrawl", white: false },
  fireworks: { file: "fireworks", white: false },
  fishaudio: { file: "fishaudio", white: false },
  "free-ai": { file: "free-ai", white: false },
  freeaiapikey: { file: "freeaiapikey", white: false },
  freebuff: { file: "freebuff", white: false },
  freeinference: { file: "freeinference", white: false },
  "freemodel-dev": { file: "freemodel-dev", white: false },
  freetheai: { file: "freetheai", white: false },
  friendli: { file: "friendli", white: false },
  frogbot: { file: "frogbot", white: false },
  "g4f-gemini": { file: "g4f-gemini", white: false },
  "g4f-groq": { file: "g4f-groq", white: false },
  "g4f-nvidia": { file: "g4f-nvidia", white: false },
  "g4f-ollama": { file: "g4f-ollama", white: false },
  "g4f-pollinations": { file: "g4f-pollinations", white: false },
  galadriel: { file: "galadriel", white: false },
  gcore: { file: "gcore", white: false },
  gemini: { file: "gemini", white: false },
  getgoapi: { file: "getgoapi", white: false },
  "ghe-copilot": { file: "ghe-copilot", white: false },
  gigachat: { file: "gigachat", white: false },
  "gitlab-duo": { file: "gitlab-duo", white: false },
  "gitlawb-gmi": { file: "gitlawb-gmi", white: false },
  gitlawb: { file: "gitlawb", white: false },
  gladia: { file: "gladia", white: false },
  glhf: { file: "glhf", white: false },
  "glm-cn": { file: "glm-cn", white: false },
  "glm-coding": { file: "glm-coding", white: false },
  gmicloud: { file: "gmicloud", white: false },
  google: { file: "google", white: false },
  gpt4all: { file: "gpt4all", white: false },
  greenpt: { file: "greenpt", white: false },
  grok: { file: "grok", white: true },
  groq: { file: "groq", white: false },
  haiper: { file: "haiper", white: false },
  hcnsec: { file: "hcnsec", white: false },
  helicone: { file: "helicone", white: false },
  helixmind: { file: "helixmind", white: false },
  helyxai: { file: "helyxai", white: false },
  heroku: { file: "heroku", white: false },
  hetzner: { file: "hetzner", white: false },
  huggingchat: { file: "huggingchat", white: false },
  huggingface: { file: "huggingface", white: false },
  hume: { file: "hume", white: false },
  hyperagent: { file: "hyperagent", white: false },
  hyperbolic: { file: "hyperbolic", white: false },
  ibm: { file: "ibm", white: false },
  ideogram: { file: "ideogram", white: false },
  iflow: { file: "iflow", white: false },
  iflytek: { file: "iflytek", white: false },
  inception: { file: "inception", white: false },
  inceptron: { file: "inceptron", white: false },
  inclusionai: { file: "inclusionai", white: false },
  inco: { file: "inco", white: false },
  infercom: { file: "infercom", white: false },
  inference: { file: "inference", white: false },
  infermatic: { file: "infermatic", white: false },
  inferx: { file: "inferx", white: false },
  inflection: { file: "inflection", white: false },
  infomaniak: { file: "infomaniak", white: false },
  "inner-ai": { file: "inner-ai", white: false },
  internlm: { file: "internlm", white: false },
  inworld: { file: "inworld", white: false },
  "io-net": { file: "io-net", white: false },
  ionos: { file: "ionos", white: false },
  iteracompute: { file: "iteracompute", white: false },
  jalapeno: { file: "jalapeno", white: false },
  jan: { file: "jan", white: false },
  "jev-api-pro": { file: "jev-api-pro", white: false },
  jiekou: { file: "jiekou", white: false },
  "jina-ai": { file: "jina-ai", white: false },
  "jina-reader": { file: "jina-reader", white: false },
  jules: { file: "jules", white: false },
  kenari: { file: "kenari", white: false },
  kie: { file: "kie", white: false },
  "kilo-gateway": { file: "kilo-gateway", white: false },
  kilocode: { file: "kilocode", white: false },
  "kimi-logomark-dark": { file: "kimi-logomark-dark", white: false },
  "kimi-logomark-light": { file: "kimi-logomark-light", white: false },
  kimi: { file: "kimi", white: false },
  kiro: { file: "kiro", white: false },
  kluster: { file: "kluster", white: false },
  koboldcpp: { file: "koboldcpp", white: false },
  "kong-ai-gateway": { file: "kong-ai-gateway", white: false },
  krutrim: { file: "krutrim", white: false },
  lambda: { file: "lambda", white: false },
  laozhang: { file: "laozhang", white: false },
  lemonade: { file: "lemonade", white: false },
  lemondata: { file: "lemondata", white: false },
  leonardo: { file: "leonardo", white: false },
  lepton: { file: "lepton", white: false },
  lilac: { file: "lilac", white: false },
  "linkup-search": { file: "linkup-search", white: false },
  liquid: { file: "liquid", white: false },
  litellm: { file: "litellm", white: false },
  literouter: { file: "literouter", white: false },
  "llama-cpp": { file: "llama-cpp", white: false },
  llamafile: { file: "llamafile", white: false },
  llamagate: { file: "llamagate", white: false },
  "llm-gateway": { file: "llm-gateway", white: false },
  "llm-kiwi": { file: "llm-kiwi", white: false },
  llm7: { file: "llm7", white: false },
  llmtr: { file: "llmtr", white: false },
  "lm-studio": { file: "lm-studio", white: false },
  lmarena: { file: "lmarena", white: false },
  lmdeploy: { file: "lmdeploy", white: false },
  localai: { file: "localai", white: false },
  logfare: { file: "logfare", white: false },
  longcat: { file: "longcat", white: false },
  luma: { file: "luma", white: false },
  lyceum: { file: "lyceum", white: false },
  magnific: { file: "magnific", white: false },
  mancer: { file: "mancer", white: false },
  maritalk: { file: "maritalk", white: false },
  martian: { file: "martian", white: false },
  maxai: { file: "maxai", white: false },
  "meganova-ai": { file: "meganova-ai", white: false },
  "merge-gateway": { file: "merge-gateway", white: false },
  meta: { file: "meta", white: false },
  metaai: { file: "metaai", white: false },
  minimax: { file: "minimax", white: false },
  mistral: { file: "mistral", white: false },
  mixedbread: { file: "mixedbread", white: false },
  mixlayer: { file: "mixlayer", white: false },
  "mlx-gemma": { file: "mlx-gemma", white: false },
  "mlx-lm": { file: "mlx-lm", white: false },
  "mlx-qwen": { file: "mlx-qwen", white: false },
  "mnn-ai": { file: "mnn-ai", white: false },
  modal: { file: "modal", white: false },
  modelscope: { file: "modelscope", white: false },
  monsterapi: { file: "monsterapi", white: false },
  moonshot: { file: "moonshot", white: false },
  morph: { file: "morph", white: false },
  "muse-code": { file: "muse-code", white: false },
  "muse-spark-web": { file: "muse-spark-web", white: false },
  "naga-ac": { file: "naga-ac", white: false },
  nanogpt: { file: "nanogpt", white: false },
  nara: { file: "nara", white: false },
  navy: { file: "navy", white: false },
  "near-ai": { file: "near-ai", white: false },
  nebius: { file: "nebius", white: false },
  neon: { file: "neon", white: false },
  nextbit: { file: "nextbit", white: false },
  "nimble-search": { file: "nimble-search", white: false },
  nlpcloud: { file: "nlpcloud", white: false },
  nomic: { file: "nomic", white: false },
  "notion-web": { file: "notion-web", white: false },
  "nous-research": { file: "nous-research", white: false },
  novita: { file: "novita", white: false },
  nscale: { file: "nscale", white: false },
  nube: { file: "nube", white: false },
  nvidia: { file: "nvidia", white: false },
  oci: { file: "oci", white: false },
  ofoxai: { file: "ofoxai", white: false },
  ollama: { file: "ollama", white: true },
  omniroute: { file: "omniroute", white: false },
  oneminai: { file: "oneminai", white: false },
  oobabooga: { file: "oobabooga", white: false },
  openadapter: { file: "openadapter", white: false },
  openai: { file: "openai", white: true },
  openclaw: { file: "openclaw", white: false },
  "opencode-go": { file: "opencode-go", white: false },
  "opencode-zen": { file: "opencode-zen", white: false },
  opencode: { file: "opencode", white: false },
  "openference-api": { file: "openference-api", white: false },
  openference: { file: "openference", white: false },
  openinference: { file: "openinference", white: false },
  openrouter: { file: "openrouter", white: false },
  openvecta: { file: "openvecta", white: false },
  openvino: { file: "openvino", white: false },
  opper: { file: "opper", white: false },
  orcarouter: { file: "orcarouter", white: false },
  orq: { file: "orq", white: false },
  ovhcloud: { file: "ovhcloud", white: false },
  parasail: { file: "parasail", white: false },
  pendra: { file: "pendra", white: false },
  perceptron: { file: "perceptron", white: false },
  perplexity: { file: "perplexity", white: false },
  phala: { file: "phala", white: false },
  phind: { file: "phind", white: false },
  piapi: { file: "piapi", white: false },
  picoclaw: { file: "picoclaw", white: false },
  pinecone: { file: "pinecone", white: false },
  pioneer: { file: "pioneer", white: false },
  plamo: { file: "plamo", white: false },
  playht: { file: "playht", white: false },
  poe: { file: "poe", white: false },
  "poixe-ai": { file: "poixe-ai", white: false },
  pollinations: { file: "pollinations", white: false },
  poolside: { file: "poolside", white: false },
  portkey: { file: "portkey", white: false },
  predibase: { file: "predibase", white: false },
  "prism-api": { file: "prism-api", white: false },
  privatemode: { file: "privatemode", white: false },
  promptql: { file: "promptql", white: false },
  publicai: { file: "publicai", white: false },
  puter: { file: "puter", white: false },
  qiniu: { file: "qiniu", white: false },
  qoder: { file: "qoder", white: false },
  qwen: { file: "qwen", white: false },
  recraft: { file: "recraft", white: false },
  regolo: { file: "regolo", white: false },
  reka: { file: "reka", white: false },
  relace: { file: "relace", white: false },
  replicate: { file: "replicate", white: false },
  requesty: { file: "requesty", white: false },
  resemble: { file: "resemble", white: false },
  "rev-ai": { file: "rev-ai", white: false },
  rime: { file: "rime", white: false },
  roocode: { file: "roocode", white: false },
  routeway: { file: "routeway", white: false },
  "routing-run": { file: "routing-run", white: false },
  runinfra: { file: "runinfra", white: false },
  runpod: { file: "runpod", white: false },
  runware: { file: "runware", white: false },
  runway: { file: "runway", white: false },
  runwayml: { file: "runwayml", white: false },
  sagg: { file: "sagg", white: false },
  "sakana-fugu": { file: "sakana-fugu", white: false },
  salad: { file: "salad", white: false },
  sambanova: { file: "sambanova", white: false },
  "sap-ai-core": { file: "sap-ai-core", white: false },
  sarvam: { file: "sarvam", white: false },
  scaleway: { file: "scaleway", white: false },
  scnet: { file: "scnet", white: false },
  scx: { file: "scx", white: false },
  sdwebui: { file: "sdwebui", white: false },
  sealion: { file: "sealion", white: false },
  searchapi: { file: "searchapi", white: false },
  "searxng-search": { file: "searxng-search", white: false },
  seekai: { file: "seekai", white: false },
  segmind: { file: "segmind", white: false },
  sensenova: { file: "sensenova", white: false },
  "serper-search": { file: "serper-search", white: false },
  sglang: { file: "sglang", white: false },
  siliconflow: { file: "siliconflow", white: false },
  snowflake: { file: "snowflake", white: false },
  "sonar-engine": { file: "sonar-engine", white: false },
  soniox: { file: "soniox", white: false },
  sparkdesk: { file: "sparkdesk", white: false },
  speechmatics: { file: "speechmatics", white: false },
  speka: { file: "speka", white: false },
  "stability-ai": { file: "stability-ai", white: false },
  stackit: { file: "stackit", white: false },
  stepfun: { file: "stepfun", white: false },
  sumopod: { file: "sumopod", white: false },
  suno: { file: "suno", white: false },
  switchpoint: { file: "switchpoint", white: false },
  synthetic: { file: "synthetic", white: false },
  "t3-web": { file: "t3-web", white: false },
  tabbyapi: { file: "tabbyapi", white: false },
  tabitoken: { file: "tabitoken", white: false },
  tavily: { file: "tavily", white: false },
  tencent: { file: "tencent", white: false },
  tensorx: { file: "tensorx", white: false },
  thebai: { file: "thebai", white: false },
  "thinking-machines": { file: "thinking-machines", white: false },
  tinfoil: { file: "tinfoil", white: false },
  "tinycms-web": { file: "tinycms-web", white: false },
  tinyfish: { file: "tinyfish", white: false },
  together: { file: "together", white: false },
  "token-kiosk": { file: "token-kiosk", white: false },
  tokenreply: { file: "tokenreply", white: false },
  tokenrouter: { file: "tokenrouter", white: false },
  topaz: { file: "topaz", white: false },
  topazlabs: { file: "topazlabs", white: false },
  trae: { file: "trae", white: false },
  triton: { file: "triton", white: false },
  truefoundry: { file: "truefoundry", white: false },
  typhoon: { file: "typhoon", white: false },
  "uc-direct": { file: "uc-direct", white: false },
  uc: { file: "uc", white: false },
  udio: { file: "udio", white: false },
  uncloseai: { file: "uncloseai", white: false },
  unify: { file: "unify", white: false },
  unorouter: { file: "unorouter", white: false },
  upstage: { file: "upstage", white: false },
  v0: { file: "v0", white: true },
  "venice-web": { file: "venice-web", white: false },
  venice: { file: "venice", white: false },
  "veoaifree-web": { file: "veoaifree-web", white: false },
  vercel: { file: "vercel", white: true },
  "vertex-ai": { file: "vertex-ai", white: false },
  "vertex-partner": { file: "vertex-partner", white: false },
  vllm: { file: "vllm", white: false },
  "void-ai": { file: "void-ai", white: false },
  volcengine: { file: "volcengine", white: false },
  voyage: { file: "voyage", white: false },
  vultr: { file: "vultr", white: false },
  wafer: { file: "wafer", white: false },
  wandb: { file: "wandb", white: false },
  watsonx: { file: "watsonx", white: false },
  wayscloud: { file: "wayscloud", white: false },
  windsurf: { file: "windsurf", white: true },
  writer: { file: "writer", white: false },
  "x-search": { file: "x-search", white: false },
  x5lab: { file: "x5lab", white: false },
  xai: { file: "xai", white: false },
  "xiaomi-mimo-token-plan": { file: "xiaomi-mimo-token-plan", white: false },
  xiaomi: { file: "xiaomi", white: false },
  xinference: { file: "xinference", white: false },
  xiurouter: { file: "xiurouter", white: false },
  "xquik-search": { file: "xquik-search", white: false },
  yandex: { file: "yandex", white: false },
  yi: { file: "yi", white: false },
  "yolo-auto": { file: "yolo-auto", white: false },
  "youcom-search": { file: "youcom-search", white: false },
  "yuanbao-web": { file: "yuanbao-web", white: false },
  "zai-web": { file: "zai-web", white: false },
  zcode: { file: "zcode", white: false },
  "zed-hosted": { file: "zed-hosted", white: false },
  zed: { file: "zed", white: false },
  "zenmux-free": { file: "zenmux-free", white: false },
  zenmux: { file: "zenmux", white: false },
  zerolimitai: { file: "zerolimitai", white: false },
  zhipu: { file: "zhipu", white: false },
  "zylo-api": { file: "zylo-api", white: false },
}

const aliases: Record<string, string> = {
  "alibaba-cn": "alibaba",
  "alibaba-coding-plan": "alibaba",
  "alibaba-coding-plan-cn": "alibaba",
  "alibaba-token-plan-cn": "alibaba",
  "aws-polly": "aws",
  "azure-cognitive-services": "azure",
  "azure-openai": "azure",
  "baidu-qianfan": "baidu",
  "bailian-coding-plan": "bailian",
  "chatgpt-web": "openai",
  "chatgpt-web-codex": "openai",
  "claude-code": "claude",
  "cloudflare-ai-gateway": "cloudflare",
  "cloudflare-playground": "cloudflare",
  "cloudflare-workers-ai": "cloudflare",
  "codex-app-server": "codex",
  "codex-cloud": "openai",
  "copilot-m365-web": "copilot",
  "copilot-web": "copilot",
  "cursor-api": "cursor",
  dashscope: "qwen",
  "deepseek-web": "deepseek",
  "doubao-web": "doubao",
  "exa-search": "exa",
  "fal-ai": "fal",
  "gemini-business": "gemini",
  "gemini-web": "gemini",
  "github-copilot": "copilot",
  "github-models": "copilot",
  "google-ai-studio": "google",
  "google-pse-search": "google",
  "grok-cli": "grok",
  "grok-web": "grok",
  "inference-net": "inference",
  "kimi-ai-coding": "kimi",
  "kimi-coding": "kimi",
  "kimi-coding-apikey": "kimi",
  "kimi-web": "kimi",
  "lambda-ai": "lambda",
  "meta-ai": "meta",
  "meta-llama": "meta",
  "minimax-cn": "minimax",
  "minimax-cn-token-plan": "minimax",
  "minimax-token-plan": "minimax",
  "moonshot-cn": "moonshot",
  "nvidia-nim": "nvidia",
  "ollama-cloud": "ollama",
  "ollama-search": "ollama",
  "perplexity-agent": "perplexity",
  "perplexity-search": "perplexity",
  "perplexity-web": "perplexity",
  "poe-web": "poe",
  "qwen-cloud": "qwen",
  "qwen-cloud-token-plan": "qwen",
  "searchapi-search": "searchapi",
  "snowflake-cortex": "snowflake",
  "stepfun-step-plan": "stepfun",
  "stepfun-step-plan-global": "stepfun",
  "tavily-search": "tavily",
  "tencent-aistudio-web": "tencent",
  "tencent-token-plan": "tencent",
  "tencent-tokenhub": "tencent",
  "v0-vercel": "v0",
  "v0-vercel-web": "v0",
  "vercel-ai-gateway": "vercel",
  "volcengine-agent-plan": "volcengine",
  "volcengine-coding-plan": "volcengine",
  "xai-oauth": "xai",
  "g4f-grok": "grok",
  g4f: "g4f-groq",
  ollamafreeapi: "ollama",
  sharedchat: "openai",
  "free2gpt-gemini": "gemini",
  free2gpt: "openai",
  netfly: "openai",
  ai365vip: "openai",
  perchance: "pollinations",
  "bing-create": "copilot",
  "microsoft-designer": "copilot",
  "stable-audio": "stability-ai",
}

export function providerIcon(slug: string): ProviderIcon | null {
  const file = aliases[slug] ?? slug
  return icons[file] ?? null
}
