export type ProviderIcon = { file: string; white: boolean }

const icons: Record<string, ProviderIcon> = {
  "360ai": { file: "360ai", white: false },
  alibaba: { file: "alibaba", white: false },
  anthropic: { file: "anthropic", white: false },
  "arcee-ai": { file: "arcee-ai", white: false },
  arcee: { file: "arcee", white: false },
  assemblyai: { file: "assemblyai", white: false },
  auggie: { file: "auggie", white: false },
  aws: { file: "aws", white: false },
  azure: { file: "azure", white: false },
  azureai: { file: "azureai", white: false },
  baichuan: { file: "baichuan", white: false },
  baidu: { file: "baidu", white: false },
  bailian: { file: "bailian", white: false },
  baseten: { file: "baseten", white: false },
  bluesminds: { file: "bluesminds", white: false },
  bytez: { file: "bytez", white: false },
  cerebras: { file: "cerebras", white: false },
  "charm-hyper": { file: "charm-hyper", white: false },
  chutes: { file: "chutes", white: false },
  "claude-web": { file: "claude-web", white: false },
  claude: { file: "claude", white: false },
  "cli-generic": { file: "cli-generic", white: false },
  cline: { file: "cline", white: false },
  cloudflare: { file: "cloudflare", white: false },
  codex: { file: "codex", white: false },
  cohere: { file: "cohere", white: false },
  comfyui: { file: "comfyui", white: false },
  continue: { file: "continue", white: false },
  copilot: { file: "copilot", white: false },
  coze: { file: "coze", white: false },
  crof: { file: "crof", white: false },
  cursor: { file: "cursor", white: false },
  deepgram: { file: "deepgram", white: false },
  deepinfra: { file: "deepinfra", white: false },
  deepseek: { file: "deepseek", white: false },
  dgrid: { file: "dgrid", white: false },
  dify: { file: "dify", white: false },
  dit: { file: "dit", white: false },
  doubao: { file: "doubao", white: false },
  elevenlabs: { file: "elevenlabs", white: false },
  exa: { file: "exa", white: false },
  factory: { file: "factory", white: false },
  fal: { file: "fal", white: false },
  fireworks: { file: "fireworks", white: false },
  freeaiapikey: { file: "freeaiapikey", white: false },
  "freemodel-dev": { file: "freemodel-dev", white: false },
  friendli: { file: "friendli", white: false },
  galadriel: { file: "galadriel", white: false },
  gemini: { file: "gemini", white: false },
  "gitlawb-gmi": { file: "gitlawb-gmi", white: false },
  gitlawb: { file: "gitlawb", white: false },
  google: { file: "google", white: false },
  grok: { file: "grok", white: true },
  groq: { file: "groq", white: false },
  hcnsec: { file: "hcnsec", white: false },
  heroku: { file: "heroku", white: false },
  huggingchat: { file: "huggingchat", white: false },
  huggingface: { file: "huggingface", white: false },
  hyperbolic: { file: "hyperbolic", white: false },
  ibm: { file: "ibm", white: false },
  iflytek: { file: "iflytek", white: false },
  inclusionai: { file: "inclusionai", white: false },
  inference: { file: "inference", white: false },
  kenari: { file: "kenari", white: false },
  "kimi-logomark-dark": { file: "kimi-logomark-dark", white: false },
  "kimi-logomark-light": { file: "kimi-logomark-light", white: false },
  kimi: { file: "kimi", white: false },
  kiro: { file: "kiro", white: false },
  krutrim: { file: "krutrim", white: false },
  lambda: { file: "lambda", white: false },
  liquid: { file: "liquid", white: false },
  llm7: { file: "llm7", white: false },
  longcat: { file: "longcat", white: false },
  meta: { file: "meta", white: false },
  metaai: { file: "metaai", white: false },
  minimax: { file: "minimax", white: false },
  mistral: { file: "mistral", white: false },
  monsterapi: { file: "monsterapi", white: false },
  moonshot: { file: "moonshot", white: false },
  morph: { file: "morph", white: false },
  nebius: { file: "nebius", white: false },
  nomic: { file: "nomic", white: false },
  novita: { file: "novita", white: false },
  nube: { file: "nube", white: false },
  nvidia: { file: "nvidia", white: false },
  ollama: { file: "ollama", white: true },
  openadapter: { file: "openadapter", white: false },
  openai: { file: "openai", white: true },
  openclaw: { file: "openclaw", white: false },
  openrouter: { file: "openrouter", white: false },
  opper: { file: "opper", white: false },
  orcarouter: { file: "orcarouter", white: false },
  ovhcloud: { file: "ovhcloud", white: false },
  perplexity: { file: "perplexity", white: false },
  phind: { file: "phind", white: false },
  picoclaw: { file: "picoclaw", white: false },
  pioneer: { file: "pioneer", white: false },
  poe: { file: "poe", white: false },
  pollinations: { file: "pollinations", white: false },
  poolside: { file: "poolside", white: false },
  publicai: { file: "publicai", white: false },
  qwen: { file: "qwen", white: false },
  recraft: { file: "recraft", white: false },
  replicate: { file: "replicate", white: false },
  requesty: { file: "requesty", white: false },
  roocode: { file: "roocode", white: false },
  runway: { file: "runway", white: false },
  sambanova: { file: "sambanova", white: false },
  searchapi: { file: "searchapi", white: false },
  sensenova: { file: "sensenova", white: false },
  snowflake: { file: "snowflake", white: false },
  sparkdesk: { file: "sparkdesk", white: false },
  stepfun: { file: "stepfun", white: false },
  sumopod: { file: "sumopod", white: false },
  suno: { file: "suno", white: false },
  "t3-web": { file: "t3-web", white: false },
  tavily: { file: "tavily", white: false },
  tencent: { file: "tencent", white: false },
  tokenrouter: { file: "tokenrouter", white: false },
  topazlabs: { file: "topazlabs", white: false },
  trae: { file: "trae", white: false },
  udio: { file: "udio", white: false },
  uncloseai: { file: "uncloseai", white: false },
  upstage: { file: "upstage", white: false },
  v0: { file: "v0", white: true },
  "veoaifree-web": { file: "veoaifree-web", white: false },
  vercel: { file: "vercel", white: true },
  vllm: { file: "vllm", white: false },
  volcengine: { file: "volcengine", white: false },
  voyage: { file: "voyage", white: false },
  wafer: { file: "wafer", white: false },
  windsurf: { file: "windsurf", white: true },
  x5lab: { file: "x5lab", white: false },
  xai: { file: "xai", white: false },
  xinference: { file: "xinference", white: false },
  yi: { file: "yi", white: false },
  "yuanbao-web": { file: "yuanbao-web", white: false },
  "zed-hosted": { file: "zed-hosted", white: false },
  "zenmux-free": { file: "zenmux-free", white: false },
  zenmux: { file: "zenmux", white: false },
  zhipu: { file: "zhipu", white: false },
}

const aliases: Record<string, string> = {
  "alibaba-coding-plan": "alibaba",
  "alibaba-coding-plan-cn": "alibaba",
  "alibaba-token-plan-cn": "alibaba",
  "azure-cognitive-services": "azure",
  "azure-openai": "azure",
  "baidu-qianfan": "baidu",
  "cloudflare-playground": "cloudflare",
  "cloudflare-workers-ai": "cloudflare",
  dashscope: "qwen",
  "google-ai-studio": "google",
  "grok-cli": "grok",
  "inference-net": "inference",
  "kimi-ai-coding": "kimi",
  "meta-ai": "meta",
  "minimax-cn": "minimax",
  "moonshot-cn": "moonshot",
  "nvidia-nim": "nvidia",
  "perplexity-agent": "perplexity",
  "qwen-cloud": "qwen",
  "qwen-cloud-token-plan": "qwen",
  "snowflake-cortex": "snowflake",
  "stepfun-step-plan": "stepfun",
  "stepfun-step-plan-global": "stepfun",
  "tencent-token-plan": "tencent",
  "tencent-tokenhub": "tencent",
  "volcengine-agent-plan": "volcengine",
  "volcengine-coding-plan": "volcengine",
}

export function providerIcon(slug: string): ProviderIcon | null {
  const file = aliases[slug] ?? slug
  return icons[file] ?? null
}
